### PR TITLE
Implemented sass 7-1-pattern

### LINKED ISSUE #5: Installing and configuration of sass-7-1-pattern
# REQUIREMENTS
Install the sass gem once installed you'll need to configure according to sass-7-1-pattern.scss 

# DESIGN
Provide references to images of the design, how it looks now, and how it should look like.

### PR DESCRIPTION
**Pull request by juperameza**
Implemented gem sass and configure it with the sass-7-1-pattern initial structure some more files may be added

Co-authored-by: AlejandroCuriel <alex_curielg@hotmail.com>

# Description
 - What?: I've added the gem for sass and created the initial files following the sass-7-1-pattern 
 - Why?: To be able to start working with sass and html

 # Testing
 No testing required.

### CODE REVIEW

**Comment by germanruzca** [comment]
LGTM :)

**Review by germanruzca — APPROVED** [review]

**Review by nallely64 — APPROVED** [review]
LGTM 😄

**Comment by alexs** [comment]
Good 👍🏻

**Review by alexs — APPROVED** [review]
Good 👍🏻

**Pull request merged**
