### PR TITLE
Feature#24/functional clock index

### LINKED ISSUE #24: Functional clock on index
# REQUIREMENTS
Update the clock on the index screen to make it auto update and show the actual time on screen. 
- Live clock
- Pure javascript
# DESIGN
image

### PR DESCRIPTION
**Pull request by nallely64**
# Description
 - What?: We've added the functional clock for the index.
 - Why?: It is important for the user to know the current hour of his check in/out.
For more information see issue #24 
  ## Screenshots

https://user-images.githubusercontent.com/43076503/160727371-3f9849da-6e13-46a7-a332-a4a35ca2f56b.mp4

### CODE REVIEW

**Review by JuanequeX — APPROVED** [review]
LGTM

**Review by YilKanda — APPROVED** [review]
LGTM!

**Review by Javi1499 — APPROVED** [review]
Nice job

**Review by EliasUR — APPROVED** [review]
LG TV 32"

**Pull request merged**
